"""
Inline-CSS HTML email template for AlphaDesk.

Gmail-compatible: no external stylesheets, no <style> blocks, no JavaScript.
All styling is applied via inline style attributes.
"""


def wrap_email_html(body_html: str, subject: str = "AlphaDesk Daily Report") -> str:
    """Wrap HTML body content in a full, Gmail-compatible email template.

    Args:
        body_html: The inner HTML content (tables, paragraphs, etc.).
        subject: Used in the header banner text.

    Returns:
        A complete HTML document string ready for email sending.
    """
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{subject}</title>
</head>
<body style="margin:0; padding:0; background-color:#f5f5f5; font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:1.6; color:#222222;">

<!-- Outer wrapper for background color -->
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f5f5f5;">
<tr>
<td align="center" style="padding:24px 12px;">

  <!-- Main container -->
  <table role="presentation" width="700" cellpadding="0" cellspacing="0" border="0" style="max-width:700px; width:100%; background-color:#ffffff; border:1px solid #e0e0e0; border-radius:4px;">

    <!-- Header -->
    <tr>
      <td style="background-color:#1a237e; padding:20px 28px; border-radius:4px 4px 0 0;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td style="font-family:Arial, Helvetica, sans-serif; font-size:22px; font-weight:bold; color:#ffffff; letter-spacing:0.5px;">
            AlphaDesk
          </td>
          <td align="right" style="font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#b0bec5;">
            {subject}
          </td>
        </tr>
        </table>
      </td>
    </tr>

    <!-- Body content -->
    <tr>
      <td style="padding:28px; font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:1.6; color:#222222;">
        {body_html}
      </td>
    </tr>

    <!-- Footer -->
    <tr>
      <td style="padding:16px 28px; border-top:1px solid #e0e0e0; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#9e9e9e; text-align:center;">
        Generated by AlphaDesk &mdash; Investment Intelligence Platform
      </td>
    </tr>

  </table>
  <!-- /Main container -->

</td>
</tr>
</table>
<!-- /Outer wrapper -->

</body>
</html>"""
